### ISSUE TITLE
Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by GSzabados** [simontb/mojio-home-assistant#21]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mojio/device_tracker.py", line 82, in _refresh
    trips = self._api.get_trips()
  File "/usr/local/lib/python3.10/site-packages/mojio_sdk/api.py", line 43, in get_trips
    return self._parse_trips(self._get_response("trips"))
  File "/usr/local/lib/python3.10/site-packages/mojio_sdk/api.py", line 78, in _parse_trips
    for json_trip_data in json_data['Data']:
KeyError: 'Data'
```

A new error what I see popping up recently. The app also has been updated a few days ago, so I can only guess, there was a change in the API.

Does any of you can see any similar?

@simontb @themoosman

**Comment by simontb** [comment]
I don't use Mojio currently, so I don't know.

**Comment by themoosman** [comment]
For some reason the list of trips aren't being returned.  Do you see trips in the mobile app? I still see trips in both.

**Comment by GSzabados** [comment]
Currently there is in the app, but it reports the device offline. The car parks inside the garage where usually is.

This message was actually from yesterday evening. I had seen it yesterday morning as well, before I restarted HA, but after the restart there wasn't any. Might be just some glitch with the server.

**Comment by themoosman** [comment]
I'll add a null check and throw a warning message.
