### ISSUE TITLE
Error setting up

### ISSUE THREAD

**Issue by OldShaterhan** [simontb/mojio-home-assistant#22]
```
Error setting up platform legacy mojio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 303, in async_setup_legacy
    setup = await hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mojio/device_tracker.py", line 41, in setup_scanner
    if not scanner.login(hass):
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mojio/device_tracker.py", line 74, in login
    self.setup(hass)
  File "/config/custom_components/mojio/device_tracker.py", line 67, in setup
    self._refresh()
  File "/config/custom_components/mojio/device_tracker.py", line 83, in _refresh
    vehicles = self._api.get_vehicles()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mojio_sdk/api.py", line 40, in get_vehicles
    return self._parse_devices(self._get_response("vehicles"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mojio_sdk/api.py", line 68, in _parse_devices
    device = Vehicle(json_vehicle_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mojio_sdk/vehicle.py", line 39, in __init__
    current_speed = json_data.get('Speed').get('Value', None)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by OldShaterhan** [comment]
Please note: I have no history, I just added device to my car ;)

**Comment by GSzabados** [comment]
@OldShaterhan, by the name in my email, I guess you are using the Smart Car in Poland. 😉 

I can confirm that is working for me without any problem.

Try to use the car first and set it up again.

**Comment by OldShaterhan** [comment]
Now I wonder a bit what email you're thinking about, but yeah, you're correct.


I made first drive using Mojio - after HA restart I don't see errors in logs anymore, but I cannot find entities/anything as well 😂

Is it anything related to my config?

```
  - platform: mojio
    domain: tmobile-pl
    client_id: <secret>
    client_secret: <secret>
    username: <mail>
    password: <pwd>
    scan_interval: 5
```

**Comment by GSzabados** [comment]
The scan interval 5 seconds is a bit harsh. The device usually updates every 1 minute according my experience. 

The entity's name should contain your plate number if you set it in the "Tracker" app.

Regarding the email, the name in the email notification from GitHub shows up as Tomasz Wieczorek, so I made a blind guess. 😉

**Comment by OldShaterhan** [comment]
Okay, seems to be working :D I have to think about how to use it. Btw. I feel it would be great to expand functionalities of this integration to similar that offer native HA car integrations ( https://www.home-assistant.io/integrations/mazda/ ) - atl east in terms of properties in read-only mode :P Unfortunately, I have no knowledge of programming in Python (except basics)
Regarding name - I forgot GitHub can show it 😆
